version: '3'
services:

  #nlp Service
  nlp:
    container_name: wenlpb_server
    hostname: nlp
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped

#Docker Networks
networks:
  default:
    external:
      name: localhost